apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent-manager
  namespace: jenkins-agents
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs:
      - get
      - list
  
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs:
      - create
  
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
  
  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - create
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-manager
  namespace: jenkins-agents
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-agent-manager
